### PR TITLE
Lg image set summary

### PR DESCRIPTION
**Pull request by redyaffle**
@iezer I made some strides on the lg-image-set-summary. It now looks like the below - this is my first attempt at monosnap giffing and it's pretty low quality :-)

style-longer

I also adjusted a few other things including the login page, and a couple of random styles: 

login

### CODE REVIEW

**Comment by redyaffle** [comment]
Oh also, I took that logo off the lion guardians website. If you think it's too much, I'm happy to take it off, but I thought it gave it a nice feel. Plus when I googled what sign-in pages look like, many had this sort of logo / input fields configuration.

**Comment by redyaffle** [comment]
Two things I think would be great additions and would really finish off the image summary: 
1) A category selector to filter the images by type (the skeleton of which I added in this PR)
2) Make the gallery images selectable so the main image gets replaced with active selection of a gallery image. 

If you have any time in the morning, we could coordinate these two items and make this very awesome!

**Comment by bantic** [comment]
looks really nice! This PR needs a rebase tho

**Comment by iezer** [comment]
Closing this. These commits are already on master. Rebased and merged a different branch.

**Pull request closed without merging**
