### PR TITLE
rework lion seach and image sets page

### PR DESCRIPTION
**Pull request by redyaffle**
@iezer The buttons aren't fully wired up yet, but I wanted to get this to you so the HTML is up to date. The search component has been modified to be much more compact, and the active element on each page is much different. The pages now look like so: 

Please let me know of any feedback, and I'll continue working through the lion search page today to incorporate all of Justin's points. 

This makes progress on the following punch list items / trello cards:
- Plain text documentation space on pages (that Justin can fill in the text of later) [Trello](https://trello.com/c/haJ0TnR0/160-3-23-leave-dummy-text-spaces-in-the-pages-for-justin-to-be-able-to-edit)
- [Image Sets Page](https://trello.com/c/HM22uawE/152-image-sets-page)
- [Lion Search Page](https://trello.com/c/rjSVMwK1/153-lion-search-page)
- [Pagination of results](https://trello.com/c/RNtovNle/155-implement-pagination-for-image-set-and-lion-search-pages-on-front-and-back-end)

screen shot 2015-05-18 at 7 12 56 am
screen shot 2015-05-18 at 7 12 47 am

### CODE REVIEW

**Comment by redyaffle** [comment]
Tweaked that last commit a bit to move around the search results count to optimize space. It now looks like so: 

screen shot 2015-05-18 at 10 48 20 am 1

**Comment by redyaffle** [comment]
@iezer Outstanding items on the image sets page include: 
- adding color coding to status (unverified, verified, etc) in the status column
- adding additional filters for metadata
- showing primary metadata in search results, and secondary metadata in the right active panel
- wiring up buttons

I'll continue working on each of these this evening, as well as continuing on the lions search page as well.

**Comment by iezer** [comment]
@redyaffle I get some test failures locally because `lg-lion-summary` is missing and that is still required on the lion search page `lion-search.hbs` I guess you'll look at that later. Travis CI is misleading because it says the build is green but in the latest build only 12 tests ran vs 218 tests on master, so it may be failing silently. I'm going out for a few hours but I can help you look at this tomorrow. Thanks.

**Comment by redyaffle** [comment]
@iezer Those test failures should be all cleaned up - sorry about that. The full test suite is running successfully locally, so hopefully it'll be a real green build this time! 

This branch now wraps up the following: 
- https://trello.com/c/rjSVMwK1/153-lion-search-page
- https://trello.com/c/RNtovNle/155-implement-pagination-for-image-set-and-lion-search-pages-on-front-and-back-end
- https://trello.com/c/haJ0TnR0/160-3-23-leave-dummy-text-spaces-in-the-pages-for-justin-to-be-able-to-edit

And the end result: 

screen shot 2015-05-19 at 12 57 42 am
screen shot 2015-05-19 at 12 57 31 am

There is one outstanding piece of functionality on the image-sets page - do you think you could wire up the Disassociate Lion button? I wasn't quite sure how to attack it and wanted to maximize checking off the small things on Justin's list as much as possible. Lmk if not. 

Finally, as more metadata is added, this will need to be expanded a bit, but it shouldn't be too hard given the current set-up.

**Comment by iezer** [comment]
@redyaffle  This is great. I'm merging now.

**Pull request merged**
